services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    volumes:
      - ./:/src/
    ports:
      - "3000:3000"
    networks:
      - faclab_network

networks:
  faclab_network:
    external: true
